### ISSUE TITLE
Icon for Fade In

### ISSUE THREAD

**Issue by harp37** [ozonos/ozon-icon-theme#104]
Icon is hardcoded by default, but "fadein" is a good name.

Original:
![fadein_original](https://cloud.githubusercontent.com/assets/1820674/5714022/b0871b44-9a88-11e4-95ac-6c41bd8b7785.png)

Suggestion:
![fadein](https://cloud.githubusercontent.com/assets/1820674/5714018/985cb344-9a88-11e4-9db0-77f5319466b6.png)

**Comment by UriHerrera** [comment]
I think it can work. @me4oslav ? Well it's better than the original that's for sure.

**Comment by me4oslav** [comment]
Much better than the original. However what is the app about, @harp37? Subtitles editor? That would explain the text editor with the video frame on top.

**Comment by UriHerrera** [comment]
It's "professional screenwriting software". @me4oslav

**Comment by me4oslav** [comment]
I see. Just a quick idea - that blue (or blue in general) does not struck me as "screenwriting" and I see the original icon uses red, so perhaps ours can be red (you know as in red curtains) or purple/violet. That blue just look like webbrowser icon blue and not scceenwriting colour.

**Comment by harp37** [comment]
![fadein](https://cloud.githubusercontent.com/assets/1820674/5724397/ea3fa65c-9b10-11e4-832a-86451a889ad9.png)
The blue was to represent that it's mostly a word processor.

**Comment by me4oslav** [comment]
Not a bad logic with the word processor either. @UriHerrera, you decide which one should get in the PR.
@harp37 once Uri has decided make a PR with the selected icon.

**Comment by UriHerrera** [comment]
Red icon, I choose you!.

**Comment by me4oslav** [comment]
@harp37 Can we have a pokeball request with the cinderhorn coloured icon, then?
