### ISSUE TITLE
Qt4 Assistant, Qt4 DbusViewer, and Qt V4L2 test Utility

### ISSUE THREAD

**Issue by mydegeneration** [ozonos/ozon-icon-theme#106]
Qt4 assistant
![assistant-qt4](https://cloud.githubusercontent.com/assets/7192681/5752049/0d147ec4-9c3c-11e4-856f-7db0bf624263.png)

Qt4 DbusViewer
![qdbusviewer-qt4](https://cloud.githubusercontent.com/assets/7192681/5752050/0fa2f828-9c3c-11e4-9557-cb2f4708d50b.png)

Qt V4L2 Test Utility
![qv4l2](https://cloud.githubusercontent.com/assets/7192681/5752058/3b2e8822-9c3c-11e4-9945-1978788921a4.png)

What do you guys suggest for these?

**Comment by me4oslav** [comment]
Well QT assistant would be the QT logo from you QT designer icon on the green background with a dark "?" below it. Sorta like this - http://www.icon2s.com/wp-content/uploads/2014/09/assistant-qt4.png
I am lost with the other two. @UriHerrera ideas?

**Comment by UriHerrera** [comment]
Same as assistant but with the arrows. What does the other software do.

**Comment by mydegeneration** [comment]
I'm not sure but here is what the About says: "This program allows easy experimenting with video4linux devices."

The only reason I'm doing these icons is because when you install a Qt app on Arch all these other dev Qt apps get installed as dependencies.

**Comment by UriHerrera** [comment]
Probably something like the icon for displays in devices.

**Comment by me4oslav** [comment]
What Uri said (for both).

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-15 13 20 15](https://cloud.githubusercontent.com/assets/7192681/5764285/bc808e02-9cbe-11e4-9ec7-a509944454b3.png)
![screenshot from 2015-01-15 13 57 45](https://cloud.githubusercontent.com/assets/7192681/5764284/bc7e9a84-9cbe-11e4-8f04-02ba5d9142fb.png)

**Comment by UriHerrera** [comment]
Color both arrows green.

**Comment by me4oslav** [comment]
I agree with @UriHerrera.
Also the dark green for the ? and the <> should be lighter. Kinda seems way too prominent.

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-15 14 26 01](https://cloud.githubusercontent.com/assets/7192681/5764787/b6e9c194-9cc2-11e4-8fce-0d9505335233.png)
![screenshot from 2015-01-15 14 26 24](https://cloud.githubusercontent.com/assets/7192681/5764788/b6f24a08-9cc2-11e4-8b40-ee1868c5cbdb.png)

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-15 14 38 14](https://cloud.githubusercontent.com/assets/7192681/5765020/48403a0a-9cc4-11e4-8bf0-b20d6274fe08.png)
![screenshot from 2015-01-15 14 30 26](https://cloud.githubusercontent.com/assets/7192681/5765023/4a83c566-9cc4-11e4-9e90-b53bc28d30ac.png)

**Comment by UriHerrera** [comment]
Yeah better.

**Comment by mydegeneration** [comment]
@UriHerrera Should I include those 2 with the other PR?

**Comment by UriHerrera** [comment]
Yes.

**Comment by me4oslav** [comment]
Can the arrows and question mar green be less froggy, though?

**Comment by mydegeneration** [comment]
What shade of green are you suggesting? Just shoot and I'll do it--I have no preference. @me4oslav

**Comment by me4oslav** [comment]
Just make the objects black and make them transparent. About 75% transparent (25% opaque should do it). And they don't really need a shadow, I guess.

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-15 19 32 06](https://cloud.githubusercontent.com/assets/7192681/5769720/504d7d1a-9ced-11e4-80fe-83a68abf4a92.png)
Any ideas?

**Comment by me4oslav** [comment]
The reason why our monitor uses full canvas symbol is because a symbol on a background like this kinda look forced and a bit too Numix. Perhaps you should also use full canvas metaphor for this app monitor icons. 
Oh and the colouring of the monitor seems bit ... erm ... not exciting to me.

**Comment by UriHerrera** [comment]
The monitor and a static background would fir the "video test" part.

**Comment by me4oslav** [comment]
Or maybe a monitor with something like a check symbol or glx gears in it?

**Comment by me4oslav** [comment]
Also, nice to see that assistant and dbus viewer are already in the repo.

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-16 18 22 18](https://cloud.githubusercontent.com/assets/7192681/5786029/bd692ac4-9dac-11e4-8a99-57a53ab754f2.png)

**Comment by UriHerrera** [comment]
Good, It'd be preferable if you did use vectors rather than clipping a bitmap.

**Comment by mydegeneration** [comment]
I also made one with a testcard
![screenshot from 2015-01-16 18 38 12](https://cloud.githubusercontent.com/assets/7192681/5786176/fa7c8e90-9dae-11e4-8231-858dd9c29def.png)

**Comment by UriHerrera** [comment]
I like this one too, use the same reflection as the other icon.

**Comment by mydegeneration** [comment]
I'm not sure on the direction of the reflection but maybe you can help me choose
![screenshot from 2015-01-16 19 16 52](https://cloud.githubusercontent.com/assets/7192681/5786503/4a15b7b0-9db4-11e4-9576-34e7cc7df470.png)
![screenshot from 2015-01-16 19 14 57](https://cloud.githubusercontent.com/assets/7192681/5786490/11ec993a-9db4-11e4-910d-2b85e26a8e95.png)

**Comment by UriHerrera** [comment]
It'd be the first one.
