### ISSUE TITLE
Avahi Server icon

### ISSUE THREAD

**Issue by mydegeneration** [ozonos/ozon-icon-theme#109]
It uses the "network-wired" icon located in "devices"
A 48x48 icon would be preferable.
![network-wired](https://cloud.githubusercontent.com/assets/7192681/5771746/403d0f06-9d12-11e4-8ab4-3e35f4415519.png)

**Comment by UriHerrera** [comment]
That icon is technically wrong.

**Comment by mydegeneration** [comment]
Should I use the network-wired-symbolic or network-server-symbolic?

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-16 00 27 27](https://cloud.githubusercontent.com/assets/7192681/5771938/9edaa86c-9d16-11e4-8975-6fb12c8e01e8.png)

**Comment by UriHerrera** [comment]
Devices icons are not as simplistic as some app icons are.

**Comment by mydegeneration** [comment]
Just showing what I have so far. If you can suggest something would be appreciated.

**Comment by UriHerrera** [comment]
Well if it's already there, a link to the ethernet icon, if it isn't, an icon resembling an ethernet port.

**Comment by me4oslav** [comment]
I am so lost with that icon. I will leave it to you guys.

**Comment by mydegeneration** [comment]
I'm gonna do a 48x48 ethernet icon since the network-wired-symbolic is only 16x16

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-16 13 23 56](https://cloud.githubusercontent.com/assets/7192681/5781729/078d15fe-9d83-11e4-848c-c9ff62276eeb.png)

**Comment by me4oslav** [comment]
I kinda like it. But like I said I will leave to @UriHerrera and you to settle on a design on this one.

**Comment by UriHerrera** [comment]
It looks the part, but, its corners are way too round. Is the port centered to the area between the screws?.

**Comment by mydegeneration** [comment]
Yeah it's centered. I'll work on those sharp corners.

**Comment by mydegeneration** [comment]
![screenshot from 2015-01-16 17 25 50](https://cloud.githubusercontent.com/assets/7192681/5785499/492ca2b4-9da5-11e4-9e7a-ef5aa0139937.png)

**Comment by me4oslav** [comment]
Better.

**Comment by UriHerrera** [comment]
Better, use linear gradients on the pins.

**Comment by mydegeneration** [comment]
With linear gradients
![screenshot from 2015-01-16 18 45 21](https://cloud.githubusercontent.com/assets/7192681/5786252/ee2d0718-9daf-11e4-9644-1f7a82bdbab2.png)

**Comment by UriHerrera** [comment]
I'm ok with this one.
