### ISSUE TITLE
Icon for GNOME MPlayer

### ISSUE THREAD

**Issue by harp37** [ozonos/ozon-icon-theme#111]
icon=gnome-mplayer

Original Icon:
![logo](https://cloud.githubusercontent.com/assets/1820674/5790898/33c37bfc-9e75-11e4-8cfd-e0e75f060f06.png)

Suggestion:
![gnome-mplayer](https://cloud.githubusercontent.com/assets/1820674/5790859/7b76e792-9e73-11e4-8083-d33c236c179a.png)

**Comment by UriHerrera** [comment]
Makes sense. I like it.

**Comment by me4oslav** [comment]
It is kinda cool. However - isn't it just a cool blue version of the VLC icon?

**Comment by KAMiKAZOW** [comment]
So? :)

**Comment by me4oslav** [comment]
What so?

**Comment by harp37** [comment]
![gnome-mplayer](https://cloud.githubusercontent.com/assets/1820674/5802356/b58c3c74-9fb9-11e4-9754-e2945d01c451.png)
Thoughts? Besides that the circle might be too big.

**Comment by me4oslav** [comment]
It will be definitely better with smaller circle and triangle. However I am bit more in favour of playing it stupid and doing a video tape and a circle with triangle.

**Comment by harp37** [comment]
![gnome-mplayer](https://cloud.githubusercontent.com/assets/1820674/5803533/bfb60fda-9fc4-11e4-9444-383dee05b179.png)

**Comment by me4oslav** [comment]
Smaller triangle and circle. You can even try triangle cut inside the circle.

**Comment by harp37** [comment]
![gnome-mplayer-3](https://cloud.githubusercontent.com/assets/1820674/5804925/d904bfee-9fcf-11e4-8183-9847814bd685.png)

**Comment by me4oslav** [comment]
Much better. However the triangle path needs moving to the right with 1px to fix the optical illusion.

**Comment by harp37** [comment]
![gnome-mplayer-3](https://cloud.githubusercontent.com/assets/1820674/5828858/3e3eafe6-a0cf-11e4-92c5-bfee50a878fc.png)
I'll submit it if that looks good.

**Comment by UriHerrera** [comment]
Looks fine to me.

**Comment by me4oslav** [comment]
Pull request is in order.
