### ISSUE TITLE
Plank/Docky and Settings icons

### ISSUE THREAD

**Issue by Deckon** [ozonos/ozon-icon-theme#113]
![plank](https://cloud.githubusercontent.com/assets/1678456/5810683/0249168a-a010-11e4-8da9-ceda1a2d1913.png)
![plank-conf](https://cloud.githubusercontent.com/assets/1678456/5810684/024df588-a010-11e4-97f1-d7ad789c6396.png)

**Comment by me4oslav** [comment]
The symbols feel overwelmingy light to  me, but I like the waves. :)
@UriHerrera, thoughts?

**Comment by UriHerrera** [comment]
I think the waves are set too high, the anchor and the gears could use a light blue gradient.

**Comment by me4oslav** [comment]
Good points. @Deckon do the necessary adjustments. 
@UriHerrera, y u no sleep?

**Comment by Deckon** [comment]
i was trying with the blue gradient  but none like me, any recommendations for the gradient?

I use lighter colors and fix the waves, add gradient ffffff(top) and eeeeee(bottom) for the anchor and the gears
![plank](https://cloud.githubusercontent.com/assets/1678456/5830920/54d61c30-a0ed-11e4-8c80-8b5e04d96fc6.png)
![plank-conf](https://cloud.githubusercontent.com/assets/1678456/5830921/54dbe21e-a0ed-11e4-8976-7ca4dc71d2d2.png)

**Comment by me4oslav** [comment]
Waves do look better now.

**Comment by Deckon** [comment]
should try something else?

**Comment by UriHerrera** [comment]
No other icon (even those made by us) have that shadow that makes logos, or objects look increasingly 3D, we do however use light colored gradients and the shadow below the logo/object.

**Comment by Deckon** [comment]
Maybe something more simple and classic?
![plank](https://cloud.githubusercontent.com/assets/1678456/5951677/d5b98a88-a72f-11e4-9aeb-50da8cc1071d.png)

**Comment by Deckon** [comment]
@UriHerrera @me4oslav 
what do you think of this?
![plank-b](https://cloud.githubusercontent.com/assets/1678456/5962785/e1df8340-a7ab-11e4-8ec4-e33b79f24c36.png)

**Comment by UriHerrera** [comment]
I think it looks great, but, there's too much going on in it. The one above it would be fine.

**Comment by me4oslav** [comment]
@Deckon @UriHerrera However we can use the second icon for some gallery/photo viewer app, right?
(provided we simplify it a tad)

**Comment by UriHerrera** [comment]
Don't we have one already?.

**Comment by Deckon** [comment]
@me4oslav 
for me it's ok

![plank](https://cloud.githubusercontent.com/assets/1678456/5986029/1175f1c8-a8b2-11e4-8dea-1cd64c265315.png)
![plank-conf](https://cloud.githubusercontent.com/assets/1678456/5986028/11760b90-a8b2-11e4-900b-727823616a07.png)

**Comment by me4oslav** [comment]
@UriHerrera We have one. I meant for app like gthumb, for example.
@Deckon I approve these last two icons. If @UriHerrera does too, you will have t make a pull request, so we can merge them upstream.

**Comment by UriHerrera** [comment]
@Deckon Make the pull request.

**Comment by Deckon** [comment]
done...now, what with the other icon?

**Comment by me4oslav** [comment]
We can use it for gthumb for example. But it needs some fixes before that.

**Comment by me4oslav** [comment]
@Deckon I saw in inkscape that symbols are not perfectly aligned to grid, which cases slight blurring in the icon. Can you fix that?

**Comment by Deckon** [comment]
ok, sorry about that, I'll fix it

I upload the .svg of the other icon here or you guys tell me what to change or what?

**Comment by me4oslav** [comment]
Okies (for both things). :)

**Comment by Deckon** [comment]
fixed, the .svg file
http://www.mediafire.com/download/fbkcg2kkn9ggegw/Plank-beach.svg

**Comment by me4oslav** [comment]
So, @Deckon what I suggest for the what we can use as another image viewer app icon is:
 - the anchor has to go, for it implies plank too much
 - make the sea bigger and perhaps add some vessel in it
 - the sun needs better colours
@UriHerrera, thoughts?

**Comment by UriHerrera** [comment]
Well first make a new issue with the preview so we can discuss it there and close this.

* Anchor must be gone.
* The eog icon has a sun, use it.
* I don't think the vessel is necessary, but there's a lot more sand than sea, m0ar sea and some subtle waves.
* *Align* everything.

**Comment by Deckon** [comment]
ok.

**Comment by me4oslav** [comment]
What @UriHerrera said. Create new issue and add the needed adjustments and we will talk in it.

**Comment by me4oslav** [comment]
Closing this issue now.
