### ISSUE TITLE
Tracker (Desktop Search/Search & Indexing) icons

### ISSUE THREAD

**Issue by mydegeneration** [ozonos/ozon-icon-theme#114]
Desktop Search
located in "actions"
![system-search](https://cloud.githubusercontent.com/assets/7192681/5829307/3cfd2aae-a0de-11e4-8a08-c36df6d2d01c.png)

Search & Indexing
located in "apps"
![tracker](https://cloud.githubusercontent.com/assets/7192681/5829320/6d297476-a0de-11e4-96d2-dc88a951b902.png)

**Comment by mydegeneration** [comment]
I'm not sure if I should just do a generic magnifying glass icon or perhaps use the ozon preferences-system-search as a template. Maybe you guys can elighten my path.

**Comment by UriHerrera** [comment]
If it's in actions is one icon, if it's in apps is a different icon. It can't be the same.

**Comment by mydegeneration** [comment]
Yeah, they're two diffent icons. I was mainly talking about the first one in my previous post because I'm confused since it's in the actions folder (which is only in the 24x24 Ozon folder).

**Comment by UriHerrera** [comment]
If it's in actions and it's being used as an application icon then the software is using the wrong icon. The icon should be mono like the rest of the icons in that folder.

**Comment by mydegeneration** [comment]
Yeah, it appears that way. I can suggest we use the /24x24/actions/search.svg icon for it but since it appears as a .desktop file I suggest we use a 48x48 icon. Not sure what to do here.

**Comment by UriHerrera** [comment]
Nothing, that's a problem by upstream. They should change the icon to be an app icon not an action icon. Then we can replace it with the proper app icon.

**Comment by me4oslav** [comment]
So, what do we do?

**Comment by UriHerrera** [comment]
We can file a bug.

**Comment by me4oslav** [comment]
It's something.

**Comment by mydegeneration** [comment]
OK so "Desktop Search" is going to be left as is. What about "Search and Indexing" which is basically Tracker?
48x48/apps/tracker.png
![tracker](https://cloud.githubusercontent.com/assets/7192681/5848601/1898f1a0-a1a8-11e4-8893-0419ef78614e.png)

**Comment by me4oslav** [comment]
Can we symlink the search icon for this?

**Comment by UriHerrera** [comment]
Yes

**Comment by me4oslav** [comment]
I will do it, then.
