### ISSUE TITLE
image viewer app

### ISSUE THREAD

**Issue by Deckon** [ozonos/ozon-icon-theme#119]
![e1df8340-a7ab-11e4-8ec4-e33b79f24c36](https://cloud.githubusercontent.com/assets/1678456/5994335/6ca68fa2-aa34-11e4-9271-55583b1cc622.png)

**Comment by me4oslav** [comment]
Add the fixes.

**Comment by Deckon** [comment]
missing the waves and the vessel

![scr](https://cloud.githubusercontent.com/assets/1678456/6044103/d66110ec-ac56-11e4-8b84-99e0dbd214a2.png)

**Comment by UriHerrera** [comment]
Add the waves. No need for a vessel.

**Comment by me4oslav** [comment]
Yeah, add some wave. And perhaps add a gradient to the see from the current blue (bottom, near the sand) to some lighter blue (top, near the horizon) to me the horizon line more blendy and less prominent.

**Comment by Deckon** [comment]
waves like this?...if not, a visual aid would help.
I use a gradient from top to bottom because the sea lost in the clouds.
![bea](https://cloud.githubusercontent.com/assets/1678456/6066176/cb4eea78-ad30-11e4-8901-05f2f2456b19.png)

**Comment by UriHerrera** [comment]
Looks fine to me.

**Comment by me4oslav** [comment]
To be too. Now the question is what which app we will use it? Gnome-photos? gThumb?

**Comment by UriHerrera** [comment]
I'd say Gnome photos.

**Comment by me4oslav** [comment]
I agree. It is a gnome app, after all. @Deckon, can we get aa pull request? the file name needed is "gnome-photos.svg".

**Comment by Deckon** [comment]
done

**Comment by me4oslav** [comment]
If you want. Contributions are always welcome. Just a different scenery icon for it would be good enough.
