### ISSUE TITLE
Gufw

### ISSUE THREAD

**Issue by mydegeneration** [ozonos/ozon-icon-theme#122]
![screenshot from 2015-02-05 23 01 44](https://cloud.githubusercontent.com/assets/7192681/6074382/262231e4-ad8b-11e4-9e36-31e823fbde84.png)

**Comment by mydegeneration** [comment]
![screenshot from 2015-02-05 21 37 29](https://cloud.githubusercontent.com/assets/7192681/6073675/6a936f52-ad7f-11e4-9017-af128a8f6dd5.png)

**Comment by mydegeneration** [comment]
![screenshot from 2015-02-05 22 42 43](https://cloud.githubusercontent.com/assets/7192681/6074259/72304f2e-ad88-11e4-8707-089fa250ba3e.png)

**Comment by mydegeneration** [comment]
![screenshot from 2015-02-05 23 13 22](https://cloud.githubusercontent.com/assets/7192681/6074465/d42dba0a-ad8c-11e4-865f-dce1ddb5a8bd.png)

**Comment by me4oslav** [comment]
Aren't they identical?

**Comment by mydegeneration** [comment]
Slight modification. Lock body is 1px higher. Any suggestions?

**Comment by me4oslav** [comment]
@UriHerrera, what do you think?

**Comment by mydegeneration** [comment]
![screenshot from 2015-02-06 14 02 00](https://cloud.githubusercontent.com/assets/7192681/6085576/01a50a16-ae09-11e4-8236-7c79c8675428.png)

**Comment by me4oslav** [comment]
Better.

**Comment by mydegeneration** [comment]
I also tried this shield size and it looks better.
![screenshot from 2015-02-07 23 28 25](https://cloud.githubusercontent.com/assets/7192681/6095254/373db8f8-af21-11e4-8076-1304e6ceee6a.png)

**Comment by UriHerrera** [comment]
It looks better.. just the wall.. maybe a more concrete looking wall?.

**Comment by mydegeneration** [comment]
@UriHerrera what do you mean??? Get rid of the bricks and use cinder blocks?

**Comment by mydegeneration** [comment]
Something like this?
![screenshot from 2015-02-09 13 01 49](https://cloud.githubusercontent.com/assets/7192681/6112114/f0421ffc-b05b-11e4-8c49-6258262d5582.png)

**Comment by me4oslav** [comment]
That's better, I think. But something about the contrast between the shield grey stroke and the new bricks irks me. Maybe the stroke should get tinted in deep orange or even become deep orange? (By deep orange I mean the previous bricks colour)

**Comment by mydegeneration** [comment]
Stroke tinted with deep orange at 30% opacity
![screenshot from 2015-02-09 13 47 19](https://cloud.githubusercontent.com/assets/7192681/6113037/497078d4-b062-11e4-9867-944eb1ab7f9f.png)

**Comment by mydegeneration** [comment]
Darker gray stroke and 15% opacity tint.
![screenshot from 2015-02-09 14 14 25](https://cloud.githubusercontent.com/assets/7192681/6113538/12b94740-b066-11e4-8446-9a77a4315485.png)

**Comment by me4oslav** [comment]
I kinda like the "Stroke tinted with deep orange at 30% opacity" option the best. How does it look with just coloured in deep orange stroke?

**Comment by mydegeneration** [comment]
![screenshot from 2015-02-09 14 25 17](https://cloud.githubusercontent.com/assets/7192681/6113777/99245b7a-b067-11e4-92ab-d5d11630d67f.png)

**Comment by me4oslav** [comment]
Now I am torn apart, dam it. :P
@UriHerrera, which one? help, dearie!

**Comment by mydegeneration** [comment]
Darker grey stroke and 30% tint
![screenshot from 2015-02-09 15 19 16](https://cloud.githubusercontent.com/assets/7192681/6114894/69049506-b06f-11e4-9eaf-cb9d63d6b278.png)

**Comment by UriHerrera** [comment]
https://github.com/ozonos/ozon-icon-theme/issues/122#issuecomment-73572639 - that one.

**Comment by me4oslav** [comment]
So, @mydegeneration, can we get a PR wit the one with the entirely orange stroke?
