### ISSUE TITLE
"view-sidebar-symbolic" is missing

### ISSUE THREAD

**Issue by satya164** [ozonos/ozon-icon-theme#124]

**Comment by me4oslav** [comment]
Where is that used?

**Comment by satya164** [comment]
Totem, and I also use it in elegance colors.

Satyajit Sahoo
Digital artist
DeviantArt Profile <http://satya164.deviantart.com>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by me4oslav** [comment]
Why can't I find it in the Adwaita icon theme symbolics folder? :o
Can't see it in Totem 31.4, either. Perhaps it was dropped in 3.14 and you need it some other symbolic (the hamburger menu one) for EC?

**Comment by satya164** [comment]
Okies. Will check.

Satyajit Sahoo
Digital artist
DeviantArt Profile <http://satya164.deviantart.com>

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by me4oslav** [comment]
Also, nice email signature. :P

**Comment by satya164** [comment]
@me4oslav lol. Thanks :D
