### ISSUE TITLE
Potential licensing issue with Skype?

### ISSUE THREAD

**Issue by Foggalong** [ozonos/ozon-icon-theme#127]
Came across [this](https://github.com/shimmerproject/elementary-xfce/pull/73#issuecomment-74901458) in an elementary XFCE issue. Should we similarly be wary of including a Skype icon in our theme by default, or should we assume that Ozon is small enough to fly under the radar?

**Comment by UriHerrera** [comment]
Like I always say whenever someone brings copyright in this context. If they really wanted to enforce their branding not only Skype, but Google, Mozilla, Adobe, and so on they would contact each and every person that has made commercial and non-commercial themes for any platform. Ever. Or let alone themes any sort of design like those found on Behance, Dribbble, devaintART, etc.

I see it as they saying: "do we get something out them not complying with our request" if they don't see a benefit they just won't bother.

**Comment by Foggalong** [comment]
Taking that as a "no" then! Issue resolved :P
