### ISSUE TITLE
Htop Icon

### ISSUE THREAD

**Issue by ebkalderon** [ozonos/ozon-icon-theme#134]
We need to link the Htop icon with utilities-system-monitor, or perhaps create a new icon based on the original logo (http://blog.trifork.com/wp-content/uploads/2014/08/htop-logo.png).
`Icon=htop`

**Comment by loctauxphilippe** [comment]
@ebkalderon does htop needs an icon? It runs only into a terminal!

**Comment by Foggalong** [comment]
It shows up in some launchers
![screenshot - 010315 - 15 46 29](https://cloud.githubusercontent.com/assets/5920259/6431526/23392fb2-c02a-11e4-9ef5-136734249dbb.png)

**Comment by loctauxphilippe** [comment]
@Foggalong I didn't know. Thanks!
