### ISSUE TITLE
position selector bug

### ISSUE THREAD

**Issue by lucazade** [ozonos/ozon-icon-theme#142]
Harddrive icon in position selector has wrong size

![bug](https://cloud.githubusercontent.com/assets/1557010/6545014/06523f7c-c56d-11e4-9525-cc79d185d11f.png)

**Comment by me4oslav** [comment]
@UriHerrera, I believe this is up to you.

**Comment by UriHerrera** [comment]
I've added it. Twice it seems.

**Comment by me4oslav** [comment]
So, is it fixed now?

**Comment by UriHerrera** [comment]
It should be.

**Comment by me4oslav** [comment]
Closing, then.
