### ISSUE TITLE
Icon Request for PopcornTime

### ISSUE THREAD

**Issue by IgorAntun** [ozonos/ozon-icon-theme#144]
Icon line says: `Icon=/usr/share/pixmaps/popcorntime.png`

![screenshot from 2015-03-10 21 24 14](https://cloud.githubusercontent.com/assets/5935946/6588104/d589882c-c76b-11e4-9e58-e2a9b543f353.png)

**Comment by me4oslav** [comment]
Icon is there, but popcorn time haardcodes the icon. You will have to change that absolute path - "/usr/share/pixmaps/popcorntime.png" to just "popcorntime". Report the hardcoded icon issue to the popcorn developers.
Closing this bug, for it is upstream bug with popcorn time.
