### ISSUE TITLE
Icon Request for Sublime Text 3

### ISSUE THREAD

**Issue by IgorAntun** [ozonos/ozon-icon-theme#145]
Icon line says: `Icon=/opt/sublime_text_3/Icon/128x128/sublime-text.png`

![screenshot from 2015-03-10 21 36 30](https://cloud.githubusercontent.com/assets/5935946/6588234/8d5acdac-c76d-11e4-9406-8bbde0ce8985.png)

**Comment by me4oslav** [comment]
Same case as with:
https://github.com/ozonos/ozon-icon-theme/issues/144
except that you should change to "sublime-text".
