### ISSUE TITLE
an Ozon GNOME maps icon is needed

### ISSUE THREAD

**Issue by sergioad** [ozonos/ozon-icon-theme#147]
Hello al the ozon community and staff, an OzonOS icon is needed for GNOME maps, this is a GNOME core application and a good maps client

Default icon=gnome-maps

I have attached the original icon here for getting inspiration :smile: 

![captura de pantalla de 2015-03-11 03 44 14](https://cloud.githubusercontent.com/assets/5375145/6593810/43857d42-c7a1-11e4-9fe6-bc3cfb542c2b.png)

**Comment by me4oslav** [comment]
Dublicate of https://github.com/ozonos/ozon-icon-theme/issues/29
Closing this, for we don't need two identical bug reports.
BTW, if an app will not be shipped out of the box, please add a community label to the issue.

**Comment by sergioad** [comment]
Ok how can I add the labels?

**Comment by me4oslav** [comment]
Just click on the labels button.

**Comment by sergioad** [comment]
Ok, thank you :smile:
