### ISSUE TITLE
Use the Numix hardcode fixer for hardcoded icons

### ISSUE THREAD

**Issue by sergioad** [ozonos/ozon-icon-theme#157]
I am suggesting to use the hardcode fixer used on the Numix icons to fix the hardcoded icons and make the apps' icons themeable :smile: what do you think?

**Comment by Foggalong** [comment]
1. Issues aren't just for icon requests
1. It's not the Numix hardcode fixer, it's an independent project
2. These aren't Numix icons, this is Ozon
3. If you check [the wiki](https://github.com/Foggalong/hardcode-fixer/wiki/Theme-Support) it will work with any theme that uses sane naming conventions

As for whether Ozon uses it as the official way, I'm way to bias to make that decision :P

**Comment by me4oslav** [comment]
I don't see much point in that, but I see no harm doing it either. It may not benefit us, but even a little benefit is good.

**Comment by Foggalong** [comment]
Fair enough!
