### ISSUE TITLE
Change colors of the folders to something not pink

### ISSUE THREAD

**Issue by zwarag** [ozonos/ozon-icon-theme#165]
Not that pink isn't a great color.
But it is one of the most unnatural color and makes it uncomfortable to use it.

I'd suggest something calmer in the blueish, light brown, maybe even greenisch area.

**Comment by Foggalong** [comment]
We do provide a range of alternative colours so if you're not happy with the pink feel free to use them :)

**Comment by zwarag** [comment]
Could you be so kind and give me a simple explanation on how to do that?
I can figure it out just need some information. Then I'd take the time to write it into your wiki for fellas who might have the same desire as me.

I tried in the gnome-tweak-tool and also had a look at the "index.theme" file.
But there does not seem to be such an option.

**Comment by Foggalong** [comment]
See here :) https://github.com/ozonos/ozon-icon-theme-folders

**Comment by me4oslav** [comment]
What @Foggalong said. Fwiw, the design reasoning behind pink is that teal and purple, which are both accent colours for Ozon are cold and if we make the folders cold, the whole feeling of coldness will get overwhelming and we don't want that.
Regarding brown-ish - folders no longer are restricted to cardboard colouring, so using no cardboard colours is perfectly fine.
