### ISSUE TITLE
netbeans icon

### ISSUE THREAD

**Issue by NexuS-Pt** [ozonos/ozon-icon-theme#92]
:+1: 
![netbeans](http://www.jlp1.com/sites/default/files/software_icon_netbeans.png)

**Comment by Deckon** [comment]
I made a few
![netbeans](https://cloud.githubusercontent.com/assets/1678456/5789734/8f867de2-9e3c-11e4-86a7-079a03227ec2.png)
![netbeans2](https://cloud.githubusercontent.com/assets/1678456/5789738/8f8eadbe-9e3c-11e4-995d-7eac9b40b66f.png)
![netbeans5](https://cloud.githubusercontent.com/assets/1678456/5789735/8f8a65c4-9e3c-11e4-99f5-9af51533b6df.png)
![netbeans7](https://cloud.githubusercontent.com/assets/1678456/5789737/8f8e8c12-9e3c-11e4-912f-e898dd47bb9f.png)
![netbeans9](https://cloud.githubusercontent.com/assets/1678456/5789736/8f8b6a1e-9e3c-11e4-919a-8990084fb806.png)

**Comment by me4oslav** [comment]
I kinda like the last option, but with a logo like this one:
http://fc07.deviantart.net/fs70/f/2014/014/f/b/netbeans_ide_modern_ui___metro_tile_icon_by_deuterianus-d726qjv.png
You can even make it darker red and use insets and dropshadow on transparent black logo to make it prominent like this:
http://icons.iconarchive.com/icons/ahdesign91/project/512/Netbeans-icon.png
Or maybe try something like this:
http://fc07.deviantart.net/fs71/i/2012/014/4/3/netbeans_flurry_icon_by_slapmefive-d4ma8ck.png
or this:
http://fc06.deviantart.net/fs71/i/2010/309/b/1/netbeans_icon_faenza_style_by_merlinthered-d328e2k.png

**Comment by Deckon** [comment]
Something like this?
![netbeans12](https://cloud.githubusercontent.com/assets/1678456/5790220/58ada7a6-9e54-11e4-8a56-052499cc67af.png)

Or if it's not broke why fix it? 
![netbeans10](https://cloud.githubusercontent.com/assets/1678456/5790224/98c5c706-9e54-11e4-93b4-bc93968dd1f8.png)

**Comment by NexuS-Pt** [comment]
the second are really cool

**Comment by Deckon** [comment]
yes, it is, that desing comes fron the nitrux icons

**Comment by me4oslav** [comment]
That second one is quite cute. @UriHerrera, anything to say?

**Comment by UriHerrera** [comment]
Yes @Deckon and for that reason it can't be in Ozon (because that's what we've avoiding, using icons from either of our own sets). The red one looks like Assaultcube.

This is more accurate to the original logo.

![](https://cloud.githubusercontent.com/assets/1678456/5789738/8f8eadbe-9e3c-11e4-995d-7eac9b40b66f.png)

**Comment by Deckon** [comment]
And this?....a little more faithful to the original icon of netbeans
![netbeans14](https://cloud.githubusercontent.com/assets/1678456/5790916/7068d6e6-9e76-11e4-8390-5f9f0c3393d3.png)

**Comment by UriHerrera** [comment]
Don't use borders on objects, just add the shadow 1px below it and it'll look good.

**Comment by Deckon** [comment]
like this?
![netbeans15](https://cloud.githubusercontent.com/assets/1678456/5791035/8fd6f5d4-9e7c-11e4-8850-2d14f787d9df.png)

**Comment by me4oslav** [comment]
Maybe add a gradient to the white symbol?

**Comment by Deckon** [comment]
@me4oslav 
![netbeans16](https://cloud.githubusercontent.com/assets/1678456/5792925/38f7d070-9ef5-11e4-9b3f-7838b241e7f5.png)

**Comment by me4oslav** [comment]
Too much. Something like eeeeee (bottom) to ffffff (top) would be ok.

**Comment by Deckon** [comment]
![netbeans16](https://cloud.githubusercontent.com/assets/1678456/5793208/f49b2330-9f00-11e4-9d96-75aec1120378.png)

**Comment by Deckon** [comment]
![netbeans16](https://cloud.githubusercontent.com/assets/1678456/5793236/168d00fc-9f02-11e4-83e0-49e449ddb3d3.png)

**Comment by me4oslav** [comment]
Yeah, that's kinda better. @UriHerrera, what do you think?

**Comment by Deckon** [comment]
a little more netbeans
![netbeans17](https://cloud.githubusercontent.com/assets/1678456/5793471/1919fa5c-9f0a-11e4-9e32-d8423957c771.png)

**Comment by me4oslav** [comment]
Ooooh, really cute.

**Comment by UriHerrera** [comment]
The *actual* Netbeans logo is the red, squiggly cube, not the smooth, perfect cube. On the other hand this last blue icon looks good.

**Comment by me4oslav** [comment]
I am really torn apart, but I am somewhat leaning towards the blue icon. Perhaps tad lighter version of it with the cube and the shadow moved 1px to the bottom, so they will look centred.

**Comment by Deckon** [comment]
@me4oslav 
I do not understand what you mean with a "lighter version".

**Comment by UriHerrera** [comment]
Lighter colors.

**Comment by me4oslav** [comment]
Yup, What Uri said - lighter coloured version.

**Comment by Deckon** [comment]
like this...or the cube too? (1px bottom)
![netbeans18](https://cloud.githubusercontent.com/assets/1678456/5794347/18f8321c-9f2f-11e4-8015-384898963008.png)

**Comment by UriHerrera** [comment]
The gradient s very dark at the bottom, make it smoother from bottom to top.

**Comment by me4oslav** [comment]
Mhm, make the bottom colour of the gradient lighter. And I guess just a taaaaaaaad lighter cube couldn't hurt.

**Comment by Deckon** [comment]
@UriHerrera  @me4oslav 
Cube and bottom lighter, the top a little bit
![netbeans18](https://cloud.githubusercontent.com/assets/1678456/5804538/5faf2178-9fcc-11e4-859a-b6d691fa41b4.png)

**Comment by me4oslav** [comment]
Better. The cube and its shadow need moving 1px to the bottom so they will look like are in the centre.

**Comment by Deckon** [comment]
done
![netbeans18](https://cloud.githubusercontent.com/assets/1678456/5804826/fe1934b4-9fce-11e4-9229-3dd361294f7c.png)

**Comment by me4oslav** [comment]
Very good. @UriHerrera, should @Deckon make a pull request for we to merge this icon?

**Comment by UriHerrera** [comment]
Yes.

**Comment by me4oslav** [comment]
@Deckon, make a pull request, then. :)

**Comment by Deckon** [comment]
done...I think so :S

**Comment by UriHerrera** [comment]
Merged.

**Comment by me4oslav** [comment]
@Deckon It doesn't show up. But no worries we have instructions to help you:
https://github.com/ozonos/ozon-icon-theme/wiki/Contributing
