### ISSUE TITLE
update manager icon

### ISSUE THREAD

**Issue by NexuS-Pt** [ozonos/ozon-icon-theme#95]
update-manager for linux mint
![screenshot from 2014-12-18 17 14 07](https://cloud.githubusercontent.com/assets/5593818/5492477/b0765b50-86d9-11e4-9897-7c94fa0e20db.png)

**Comment by me4oslav** [comment]
Just remembered about this icon. :P
@UriHerrera should I put it in the icon theme and close the issue or leave the issue for the community to cover?

**Comment by UriHerrera** [comment]
Yeah, though we won't actually use it.

**Comment by me4oslav** [comment]
Okies. I will push it.
